### ISSUE TITLE
AFFECTS_TRACK changes extra lights specular

### ISSUE THREAD

**Issue by Trava715** [ac-custom-shaders-patch/acc-extension-config#158]
AFFECTS_TRACK = 0
![image](https://user-images.githubusercontent.com/43389722/147144178-6bb843dd-514c-4fe8-b9ba-2c68b77dc5a3.png)

AFFECTS_TRACK = 1
![image](https://user-images.githubusercontent.com/43389722/147144204-bdfcff02-b926-46d9-8dec-073688712db7.png)

**Comment by gro-ove** [comment]
Set `NO_SELF_SPECULAR = 0`. By default it’s true for lights that illuminate track, meaning that light would produce speculars when illuminating track or other cars but not its own car.

Had to add it because having a single point specular for things like large brake lights right below them, when light is large but specular is tiny looked weird.
