### ISSUE TITLE
Black screen after loading in-game

### ISSUE THREAD

**Issue by Trava715** [ac-custom-shaders-patch/acc-extension-config#185]
![image](https://user-images.githubusercontent.com/43389722/150815045-d19e5ae9-7e95-4989-95b4-bc5ed3c021e7.png)

Seems to happen more often when loading a car with unpacked data, been present since at least CSP 1.61 and still happens as of 1.74 public.
Also occurs randomly after a hot config reload.

**Comment by gro-ove** [comment]
Switching PP-filter helps, right? Sadly this bug is something I’m still trying to figure out. Happens a bit too rarely to reliably debug… Sometimes even switching PP-filter during the race triggers it, so my recent attempt to simply switch PP-filter automatically after loading turned out to not help at all.

**Comment by Trava715** [comment]
Reloading ext_config seems to trigger it quite consistently.

**Comment by Marocco2** [comment]
Still present in 0.1.77 public?

**Comment by Trava715** [comment]
Appears to be fixed in 1.78, can't repro it with config reloads. Would like confirmation from multiple users though.

**Comment by Marocco2** [comment]
Closed due to inactivity and being possibly fixed

**Comment by Kurohitsugi9** [comment]
I had this behavior if I use the Tunnel script in CSP -> Graphic Adjustments -> Scriptable filters.
