### ISSUE TITLE
[CAR INSTRUMENTS] Game crashes during loading with mod enabled (Ubuntu Linux, Proton version 5.0)

### ISSUE THREAD

**Issue by ptriantafy** [ac-custom-shaders-patch/acc-extension-config#326]
I am using CSP version 0.1.78, it worked fine until i tried driving the Porsche Panamera (which uses the car instruments mod). The game crashed during "final steps" in loading screen. Even with Spotify and Firefox closed it kept crashing. The .zip attached containts the .report file produced by the crash, I hope it helps. After I disabled the mod the game worked fine again.
CM version: 0.8.2393.39063
Ubuntu Version: 22.04
[gameCrashLogs.zip](https://github.com/ac-custom-shaders-patch/acc-extension-config/files/10042868/gameCrashLogs.zip)

**Comment by subanz** [comment]
This is most likely caused by missing Windows fonts. Or at least thats what stopped the Car Instruments crash for me. 

You might be able to install the fonts through Protontrick/Winetricks although I'm not sure that has all the necessary fonts.

These might be the necessary fonts after looking through an error log, although I copied all fonts from Windows so there might be others to fix it.

Failed to load IMGUI font: C:\windows\Fonts/verdana.ttf
Failed to load IMGUI font: C:\windows\Fonts/verdana.ttf
Failed to load IMGUI font: C:\windows\Fonts/verdana.ttf
Failed to load IMGUI font: C:\windows\Fonts/segoeui.ttf
Failed to load IMGUI font: C:\windows\Fonts/verdanai.ttf

The way I deal with it is by copying the fonts folder(C:\Windows\Fonts) from a Windows install(I know it sucks and its kind of a legaly murky area and its why Wine/Proton don't just do it this way).
If you want to this also you can either copy all the fonts to ".../steamapps/compatdata/244210/pfx/drive_c/windows/Fonts/" or symlink them to that folder.
